env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-console": "off",
  "import/extensions": 0,
  "no-continue": 0,
  "indent": 0
}
